### ISSUE TITLE
historical_quotes example does not work

### ISSUE THREAD

**Issue by tllucero** [cometaworks/yahoo_finanza#17]
historical_quotes = yahoo_finanza_client.quotes_history('AAPL', '2012-03-10', '2013-03-10' )

I get the error:

 yahoo_finanza-0.4.8/lib/yahoo_finanza/client.rb:13:in `quotes_history': wrong number of arguments (given 3, expected 2) (ArgumentError)

**Comment by jonahoffline** [comment]
@tllucero hey, it looks like the example is wrong. Just verified the source, and the method expects the date inside a hash like:
```Ruby
options = { start_date: '2012-03-10', end_date: '2013-03-10' }
historical_quotes = yahoo_finanza_client.quotes_history('AAPL', options)
```
Hope this helps!
